routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\ProductController;
use App\Http\Controllers\Admin\ProductController as AdminController;
use App\Http\Controllers\Admin\PriceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->prefix('products')->name('products')->group(function(){

    Route::get('create', [AdminController::class, 'create'])->name('.create');
    Route::post('', [AdminController::class, 'store'])->name('.store');
    Route::get('{product}/edit', [AdminController::class, 'edit'])->name('.edit');
    Route::patch('{product}', [AdminController::class, 'update'])->name('.update');
    Route::delete('{product}', [AdminController::class, 'destroy'])->name('.delete');

    Route::prefix('{product}/prices')->name('.prices')->group(function(){

        Route::post('store', [PriceController::class, 'store'])->name('.store');
        Route::delete('{price}', [PriceController::class, 'destroy'])->name('.delete');

    });
});

Route::get('', [ProductController::class, 'index'])->name('index');
Route::get('{product}', [ProductController::class, 'show'])->name('show');

app/Models/Price.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Price extends Model
{
    use HasFactory;

    protected $fillable = [
        'product_id',
        'value',
    ];

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function valueFormatted(): string
    {
        return '$' . number_format($this->value / 100, 2);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
    ];

    public function prices()
    {
        return $this->hasMany(Price::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Admin/PriceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\StorePriceRequest;
use App\Models\Product;
use App\Models\Price;

class PriceController extends Controller
{
    public function store(StorePriceRequest $request, Product $product)
    {
        $price = $product->prices()->create($request->only([
            'value',
        ]));

        return redirect()->route('products.edit', $product);
    }

    public function destroy(Request $request, Product $product, Price $price)
    {
        $product->prices()->where('id', $price->id)->delete();

        return redirect()->route('products.edit', $product);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\StoreProductsRequest;
use App\Http\Requests\UpdateProductsRequest;

use App\Models\Product;

class ProductController extends Controller
{
    public function create(Request $request)
    {
        return view('admin.create');
    }

    public function store(StoreProductsRequest $request)
    {
        $product = Product::create($request->only([
            'name',
            'description',
        ]));

        return redirect()->route('products.edit', $product);
    }

    public function edit(Request $request, Product $product)
    {
        return view('admin.edit', [
            'product' => $product
        ]);
    }

    public function update(UpdateProductsRequest $request, Product $product)
    {
        $product->update($request->only([
            'name',
            'description',
        ]));

        return redirect()->route('products.edit', $product);
    }

    public function destroy(Request $request, Product $product)
    {
        $product->delete();

        return redirect()->route('index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Product;
use App\Services\Listings\ProductListing;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $listing = new ProductListing($request->all(), Product::withCount('prices'));

        return view('index', [
            'products' => $listing->paginate(),
        ]);
    }

    public function show(Request $request, Product $product)
    {
        return view('show', [
            'product' => $product
        ]);
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

class ProfileController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function edit(Request $request): View
    {
        return view('profile.edit', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $request->user()->fill($request->validated());

        if ($request->user()->isDirty('email')) {
            $request->user()->email_verified_at = null;
        }

        $request->user()->save();

        return Redirect::route('profile.edit')->with('status', 'profile-updated');
    }

    /**
     * Delete the user's account.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current_password'],
        ]);

        $user = $request->user();

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }
}

resources/views/admin/create.blade.php
@extends('admin.layout')

@section('content')

<h2>Create product</h2>

<form method="POST" action="{{ route('products.store') }}">
    {{ csrf_field() }}

    <h4>name</h4>
    <div>
        <input type="text" name="name" placeholder="name" />
    </div>
    <h4>description</h4>
    <div>
        <textarea name="description"></textarea>
    </div>

    <h4>prices (space separated)</h4>
    <div>
        <input type="text" name="prices" placeholder="eg: 10.00, 0.99" />
    </div>
    <button>submit</button>
</form>


@endsection

resources/views/admin/edit.blade.php
@extends('admin.layout')

@section('content')

<h2>Edit product {{ $product->id }}</h2>

<form method="POST" action="{{ route('products.update', $product) }}">
    {{ csrf_field() }}
    {{ method_field('PATCH') }}

    <h4>name</h4>
    <div>
        <input type="text" name="name" placeholder="name" value="{{ $product->name }}" />
    </div>
    <h4>description</h4>
    <div>
        <textarea name="description">{{ $product->description }}</textarea>
    </div>

    <h4>prices</h4>

    <ul>
        @foreach($product->prices as $price)
            <li>
                {{ $price->valueFormatted() }}

                @auth
                <form method="POST" action="{{ route('products.prices.delete', [$product, $price]) }}">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button>delete</button>
                </form>
                @endauth
            </li>
        @endforeach

    </ul>

    <h4>add price</h4>
    <form action="{{ route('products.prices.store', $product) }}" method="POST">
        {{ csrf_field() }}
        <input type="text" name="value" placeholder="value in cents" />
    </form>
    <button>submit</button>
</form>


@endsection

resources/views/admin/layout.blade.php
<html>
    <head>
        <title>An admin app</title>
    </head>
    <body>

        <div>
            <a href="{{ route('index') }}">listinig</a>
            <a href="{{ route('products.create') }}">create</a>
            <form action="{{ route('logout') }}" method="post">
                {{ csrf_field() }}
                <button>logout</button>
            </form>
        </div>

        @yield('content')

    </body>
</html>

resources/views/index.blade.php
@extends('layout')

@section('content')

{{-- this is intentionsl -> no need to fight with css ansd so on for backend dev position --}}

<style>
    svg {
        display: none;
    }
    form {
        display: grid;
        grid-gap: 1em;
        grid-template-columns: repeat(4, 1fr)
    }

    table {
        width: 100%;
        border: black 1px solid
    }

    table td {
        border-top: black 1px solid
    }

    table th {
        text-align: left
    }

</style>

<div>
    @auth
        <a href="{{ route('products.create') }}">create</a>
        <form action="{{ route('logout') }}" method="post">
            {{ csrf_field() }}
            <button>logout</button>
        </form>
    @endauth
    @guest
        <a href="{{ route('login') }}">login</a>
    @endguest
</div>
<h2>Products listing</h2>


<form>
    <div>
        <div>
            filter by name
        </div>
        <input type="text" name="name" placeholder="filter by name" value="{{ request()->name }}" />
    </div>
    <div>
        <div>
            sorting order
        </div>
        <select name="direction">
            @foreach(\App\Enums\SortingOrder::cases() as $case)
                <option value="{{ $case->value }}" {{ request()->direction === $case->value ? 'selected' : '' }}>name {{ $case->value }}</option>
            @endforeach
        </select>
    </div>

    <button>apply</button>
</form>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>prices count</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach($products as $product)
        <tr>
            <td>{{ $product->id }}</td>
            <td>{{ $product->name }}</td>
            <td>{{ $product->prices_count }}</td>
            <td>
                <a href="{{ route('show', $product) }}">show</a>

                @auth
                    <a href="{{ route('products.edit', $product) }}">edit</a>

                    <form action="{{ route('products.delete', $product) }}">
                        {{ method_field('DELETE')}}
                        <button>delete</button>
                    </form>
                @endauth

            </td>
        </tr>
        @endforeach
    </tbody>
</table>

{!! $products->links() !!}

@endsection

resources/views/layout.blade.php
<html>
    <head>
        <title>An app</title>
    </head>
    <body>

        @yield('content')

    </body>
</html>

resources/views/login.blade.php
@extends('layout')

@section('content')

<h2>Login</h2>

<form method="POST">
    {{ csrf_field() }}
    <div>
        <input type="email" name="email" placeholder="email" value="admin@example.com" />
    </div>
    <div>
        <input type="password" name="password" placeholder="password" value="password" />
    </div>
    <button>login</button>
</form>


@endsection

resources/views/show.blade.php
@extends('layout')

@section('content')

<div>
    <a href="{{ route('index') }}">back to listinig</a>
    @auth
        <a href="{{ route('products.edit', $product) }}">edit</a>
    @endauth
</div>

<h2>{{ $product->name }}</h2>
<p>{!! nl2br($product->description) !!}</p>


<h4>Price variants</h4>
<ul>
    @foreach($product->prices as $price)
        <li>{{ $price->valueFormatted() }}</li>
    @endforeach
</ul>

@endsection